### ISSUE TITLE
[DEV] Ingest-accessioner failed to connect to RabbitMQ

### ISSUE THREAD

**Issue by danielvaughan** [HumanCellAtlas/ingest-central#21]
**Give the bug a title**

``` 2018-05-27 16:39:48,021  - pika.callback - ERROR in callback.py:239 process(): Calling <bound method SelectConnection._on_connection_error of <SelectConnection INIT socket=None params=<URLParameters host=100.68.204.122 port=5672 virtual_host=/ ssl=False>>> for "0:_on_connection_error" failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 1768, in _on_connection_error
    self.params.connection_attempts)
AMQPConnectionError: Connection to 100.68.204.122:5672 failed: timeout
Traceback (most recent call last):
  File "accession-app.py", line 30, in <module>
    listener.run()
  File "/app/listener.py", line 321, in run
    self._connection.ioloop.start()
  File "/usr/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/usr/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/usr/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 1836, in _on_connect_timer
    error)
  File "/usr/lib/python2.7/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/usr/lib/python2.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 1768, in _on_connection_error
    self.params.connection_attempts)
pika.exceptions.AMQPConnectionError: Connection to 100.68.204.122:5672 failed: timeout
```

**To Reproduce**
scaled replicas to 0 and then to 15. 2 pods had this error.

**Expected behaviour**

All pods connect

**Actual behaviour**

2/15 failed to connect

**Comment by danielvaughan** [comment]
Could this be fixed by using the alternative to Pika?

**Comment by danielvaughan** [comment]
I believe this to be due to the dns policy of the pod now corrected. Reopen if reoccurs
