### ISSUE TITLE
[Integration] Errors reported in logs from state tracking

### ISSUE THREAD

**Issue by danielvaughan** [HumanCellAtlas/ingest-central#23]
**Give the bug a title**

These two errors occur frequently in integration environment state tracking:

```
2018-05-26 09:49:40.941  INFO 6 --- [pool-1-thread-1] o.h.i.s.monitor.SubmissionStateUpdater   : Updating state of envelope with ID 5b092daeac80bd00077123c2 to state VALIDATING
2018-05-26 11:17:05.687  INFO 6 --- [cTaskExecutor-1] o.h.i.s.monitor.SubmissionStateListener  :        Created Envelope 'aedc774d-6583-49c3-98ce-c8db0c876751'
2018-05-26 11:17:05.688  WARN 6 --- [cTaskExecutor-1] o.s.s.l.CompositeStateMachineListener    : Error during stateChanged

java.lang.NullPointerException: null

```

```
2018-05-25 16:15:29.941  INFO 6 --- [pool-1-thread-1] o.h.i.s.monitor.SubmissionStateUpdater   : Updating state of envelope with ID 5b0835dcac80bd0007712325 to state PENDING
2018-05-25 16:15:29.943 ERROR 6 --- [pool-1-thread-1] o.h.i.s.monitor.SubmissionStateUpdater   : Failed to update state in the core

org.humancellatlas.ingest.exception.CoreStateUpdatedFailedException: Failed to updated state of envelope with ID 5b0835dcac80bd0007712325 to state PENDING
        at org.humancellatlas.ingest.state.monitor.SubmissionStateUpdater.update(SubmissionStateUpdater.java:67) [classes!/:na]
        at org.humancellatlas.ingest.state.monitor.SubmissionStateUpdater.update(SubmissionStateUpdater.java:72) [classes!/:na]
        at org.humancellatlas.ingest.state.monitor.SubmissionStateUpdater.persistStates(SubmissionStateUpdater.java:84) [classes!/:na]
        at org.humancellatlas.ingest.state.monitor.SubmissionStateUpdater.lambda$init$0(SubmissionStateUpdater.java:95) [classes!/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_172]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_172]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_172]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]
Caused by: java.lang.IllegalArgumentException: Relation must not be null or empty!
        at org.springframework.util.Assert.hasText(Assert.java:276) ~[spring-core-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.hateoas.client.Hop.rel(Hop.java:60) ~[spring-hateoas-0.24.0.RELEASE.jar!/:na]
        at org.springframework.hateoas.client.Traverson$TraversalBuilder.follow(Traverson.java:275) ~[spring-hateoas-0.24.0.RELEASE.jar!/:na]
        at org.springframework.hateoas.client.Traverson.follow(Traverson.java:225) ~[spring-hateoas-0.24.0.RELEASE.jar!/:na]
        at org.humancellatlas.ingest.client.IngestApiClient.updateEnvelopeState(IngestApiClient.java:78) ~[classes!/:na]
        at org.humancellatlas.ingest.state.monitor.SubmissionStateUpdater.update(SubmissionStateUpdater.java:54) [classes!/:na]
        ... 10 common frames omitted

```

**Comment by danielvaughan** [comment]
@rolando-ebi said these were not a problem but they should be removed in future as they pollute the logs

**Comment by justincc** [comment]
@rolando-ebi is this still an issue?

**Comment by rolando-ebi** [comment]
@justincc Yes but shouldn't affect the system
