### ISSUE TITLE
Resolve spamming of ingest core log with org.springframework.dao.OptimisticLockingFailureException

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#232]
Ingest core log is getting continually spammed with exceptions of the form 

```
org.springframework.dao.OptimisticLockingFailureException: Optimistic lock exception on saving entity: {_class=org.humancellatlas.ingest.file.File, fileName=0eac9052-27b1-49fa-8d84-6246075fddf5.zarr!cell_metadata_string_name!0, dataFileUuid=ab408061-523a-4de8-936c-fdbed5c2f6ad, content={ "describedBy" : "http://schema.staging.data.humancellatlas.org/type/file/5.3.4/analysis_file" , "schema_type" : "file" , "file_core" : { "file_name" : "0eac9052-27b1-49fa-8d84-6246075fddf5.zarr!cell_metadata_string_name!0" , "file_format" : "unknown"}}, validationState=DRAFT, version=1, submissionDate=Thu Nov 01 10:44:52 GMT 2018, updateDate=Thu Nov 01 10:44:56 GMT 2018, lastModifiedUser=anonymousUser, type=FILE, uuid={ "uuid" : { "$uuid" : "343fcc2e-c103-4798-89f5-708732d3a482"}}, events=[ ], inputToProcesses=[ ], derivedByProcesses=[ { "$ref" : "process" , "$id" : { "$oid" : "5bdad921f31a6a00072b14a7"}}], submissionEnvelopes=[ { "$ref" : "submissionEnvelope" , "$id" : { "$oid" : "5bdad921f31a6a00072b14a5"}}]} to collection file
	at org.springframework.data.mongodb.core.MongoTemplate$12.doInCollection(MongoTemplate.java:1183) ~[spring-data-mongodb-1.10.6.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate$12.doInCollection(MongoTemplate.java:1156) ~[spring-data-mongodb-1.10.6.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:482) ~[spring-data-mongodb-1.10.6.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doUpdate(MongoTemplate.java:1156) ~[spring-data-mongodb-1.10.6.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doSaveVersioned(MongoTemplate.java:1024) ~[spring-data-mongodb-1.10.6.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:988) ~[spring-data-mongodb-1.10.6.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.save(SimpleMongoRepository.java:82) ~[spring-data-mongodb-1.10.6.RELEASE.jar!/:na]
```

From a conversation with @aaclan-ebi it sounds like these occur when two services are trying to update that document at the same time (e.g. validation and accession). I suggest that we

1. Assess whether this is what we want. For example, would it be better to queue these requests rather than requiring services to retry?
1. If this is what we want then see if we can track this another way (e.g. keeping an OptimisticLockingFailureException statistic) rather than spamming the logs with big exception traces on every occurrence.

**Comment by rolando-ebi** [comment]
This shouldn't happen anymore after deprecating the old addInputBundle() endpoint, once greenbox move to the new endpoint(s)
