### ISSUE TITLE
Optimistic lock exception when adding input bundle reference

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/ingest-central#38]
When creating a submission envelope to submit analysis results from the greenbox back to ingest, the request to the `/bundleReferences` endpoint to add a reference to the input bundle sometimes fails with a 409 optimistic lock exception error. This error has appeared in two scale tests containing 1000 bundles. 

Example submission envelope: http://api.ingest.integration.data.humancellatlas.org/processes/5b159d34ac80bd000771b7a0

```
Traceback (most recent call last):
  File "/usr/local/bin/create-envelope", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pipeline_tools/create_envelope.py", line 230, in main
    run(args.submit_url, args.analysis_json_path, args.schema_version)
  File "/usr/local/lib/python2.7/site-packages/pipeline_tools/create_envelope.py", line 49, in run
    add_input_bundles(input_bundles_url, auth_headers, analysis_json_contents, http_requests)
  File "/usr/local/lib/python2.7/site-packages/pipeline_tools/create_envelope.py", line 139, in add_input_bundles
    response = http_requests.put(input_bundles_url, headers=auth_headers, json=bundle_refs_js)
  File "/usr/local/lib/python2.7/site-packages/pipeline_tools/http_requests.py", line 116, in put
    return self._http_request_with_retry(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipeline_tools/http_requests.py", line 165, in _http_request_with_retry
    )(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tenacity/__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/tenacity/__init__.py", line 330, in call
    start_time=start_time)
  File "/usr/local/lib/python2.7/site-packages/tenacity/__init__.py", line 279, in iter
    return fut.result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/site-packages/tenacity/__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipeline_tools/http_requests.py", line 229, in _http_request
    HttpRequests.check_status(response)
  File "/usr/local/lib/python2.7/site-packages/pipeline_tools/http_requests.py", line 287, in check_status
    raise requests.HTTPError(message, response=response)
requests.exceptions.HTTPError: HTTP status code 409 is not in expected range 2xx. Response: {"url":"http://api.ingest.integration.data.humancellatlas.org/processes/5b159d34ac80bd000771b7a0/bundleReferences","exceptionMessage":" Optimistic lock exception on saving entity: ...
```

**Comment by danielvaughan** [comment]
Thanks, I have added this to our current sprint and we will resolve this as a priority.

https://www.ebi.ac.uk/panda/jira/browse/HCA-981

**Comment by aaclan-ebi** [comment]
Fix was deployed to production last 17th July.

**Comment by samanehsan** [comment]
We are now seeing this issue when sending a request to link the analysis protocol to the analysis process when creating the submission envelope using the URL "http://api.ingest.integration.data.humancellatlas.org/processes/5b91771a12bf39000bdc32da/protocols"

**Comment by rolando-ebi** [comment]
@samanehsan Do you have exact details of the HTTP/curl request?

**Comment by samanehsan** [comment]
@rolando-ebi, here's the stack trace that we saw after making a PUT request to `http://api.ingest.integration.data.humancellatlas.org/processes/5b91771a12bf39000bdc32da/protocols` in the submission workflow [here](https://github.com/HumanCellAtlas/pipeline-tools/blob/master/pipeline_tools/create_envelope.py#L88):
```
Traceback (most recent call last):
  File "/usr/local/bin/create-envelope", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pipeline_tools/create_envelope.py", line 381, in main
    analysis_file_version=args.analysis_file_version)
  File "/usr/local/lib/python3.6/site-packages/pipeline_tools/create_envelope.py", line 90, in build_envelope
    http_requests=http_requests)
  File "/usr/local/lib/python3.6/site-packages/pipeline_tools/create_envelope.py", line 353, in link_analysis_protocol_to_analysis_process
    response = http_requests.put(link_url, headers=link_headers, data=analysis_protocol_url)
  File "/usr/local/lib/python3.6/site-packages/pipeline_tools/http_requests.py", line 133, in put
    return self._http_request_with_retry(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipeline_tools/http_requests.py", line 187, in _http_request_with_retry
    )(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 330, in call
    start_time=start_time)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 279, in iter
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipeline_tools/http_requests.py", line 251, in _http_request
    HttpRequests.check_status(response)
  File "/usr/local/lib/python3.6/site-packages/pipeline_tools/http_requests.py", line 317, in check_status
    raise requests.HTTPError(message, response=response)
requests.exceptions.HTTPError: HTTP status code 409 is not in expected range 2xx. Response: {"url":"http://api.ingest.integration.data.humancellatlas.org/processes/5b91771a12bf39000bdc32da/protocols","exceptionMessage":"Optimistic lock exception on saving entity
```

**Comment by rolando-ebi** [comment]
This shouldn't happen anymore after the deprecated addInputBundle() endpoint is removed
