### ISSUE TITLE
Fix regex check for date format of `updateDate` in the exporter

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#464]
**Steps to reproduce**:
1. Do a submission which will produce 1 bundle
2. Before submitting, update the updateDate of one metadata that will be included in the bundle 
    *I made up this step, not even sure if the updateDate can be patched. This is actually an intermittent scenario where a document has been updated at a time without a fraction of second.*
3. submit the submission

**Actual Behaviour**:
Submission is stuck in Processing'
Log shows that an error occured:
```
2019-07-16 11:05:11,889  - ingest.api.dssapi - INFO in dssapi.py:76 put_file(): Creating file in DSS 40704b4e-dfd4-4b3f-97aa-8baebbb9d1db:2019-07-16T110309.379000Z with params: {"uuid": "40704b4e-dfd4-4b3f-97aa-8baebbb9d1db", "version": "2019-07-16T110309.379000Z", "creator_uid": 8008, "source_url": "s3://org-humancellatlas-upload-staging/f7586328-6593-47c9-add5-d926029cb867/sequence_file_40704b4e-dfd4-4b3f-97aa-8baebbb9d1db.json", "bundle_uuid": "7c6ff940-a6ea-468a-96f6-caa080d6e4f1"}
 2019-07-16 11:05:12,155  - ingest.api.dssapi - INFO in dssapi.py:95 put_file(): Created!
 2019-07-16 11:05:12,515  - receiver.CreateBundleReceiver - ERROR in receiver.py:74 on_message(): 400 Client Error:  for url: http://172.20.105.197/submissionEnvelopes/5d2dae8f5f9ee9000809b679/submissionErrors
Traceback (most recent call last):
  File "/app/src/hca-ingest/ingest/exporter/ingestexportservice.py", line 452, in put_files_in_dss
    created_file = self.dss_api.put_file(bundle_uuid, bundle_file)
  File "/app/src/hca-ingest/ingest/api/dssapi.py", line 55, in put_file
    version = utils.to_dss_version(update_date) if update_date \
  File "/app/src/hca-ingest/ingest/api/utils.py", line 10, in to_dss_version
    date = parse_date_string(date_str)
  File "/app/src/hca-ingest/ingest/api/utils.py", line 20, in parse_date_string
    raise ValueError(f'unknown date format for [{date_str}]')
ValueError: unknown date format for [2019-07-16T11:03:09Z]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/hca-ingest/ingest/exporter/ingestexportservice.py", line 122, in export_bundle
    created_files = self.put_files_in_dss(bundle_uuid, bundle_files, process_info)
  File "/app/src/hca-ingest/ingest/exporter/ingestexportservice.py", line 456, in put_files_in_dss
    raise FileDSSError('An error occurred while putting file in DSS' + str(e))
ingest.exporter.ingestexportservice.FileDSSError: An error occurred while putting file in DSSunknown date format for [2019-07-16T11:03:09Z]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/receiver.py", line 71, in on_message
    process_uuid=body_dict["documentUuid"])
  File "/app/src/hca-ingest/ingest/exporter/ingestexportservice.py", line 145, in export_bundle
    self.ingest_api.create_submission_error(submission_url, json.dumps(report))
  File "/app/src/hca-ingest/ingest/api/ingestapi.py", line 330, in create_submission_error
    return self.create_entity(submission_url, data, 'submissionErrors')
  File "/app/src/hca-ingest/ingest/api/ingestapi.py", line 341, in create_entity
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: http://172.20.105.197/submissionEnvelopes/5d2dae8f5f9ee9000809b679/submissionErrors
 2019-07-16 11:05:12,529  - receiver.CreateBundleReceiver - ERROR in receiver.py:75 on_message(): Failed to process the exporter message: {"bundleUuid":"7c6ff940-a6ea-468a-96f6-caa080d6e4f1","versionTimestamp":"2019-07-16T11:03:43.669256Z","messageProtocol":null,"documentId":"5d2dae915f9ee9000809b695","documentUuid":"e9e14744-e41f-4f60-92e3-ed9de1265d84","callbackLink":"/processes/5d2dae915f9ee9000809b695","documentType":"Process","envelopeId":"5d2dae8f5f9ee9000809b679","envelopeUuid":"f7586328-6593-47c9-add5-d926029cb867","index":0,"total":1} due to error: 400 Client Error:  for url: http://172.20.105.197/submissionEnvelopes/5d2dae8f5f9ee9000809b679/submissionErrors
 2019-07-15 16:05:37,
```

**Expected behaviour**:
updateDate must be converted without an error
File should be created in the data store
Bundle must be created

**Dev notes**:
There's a part in our code which checks the expected format of the updateDate of our documents in Ingest. This date value needs to be converted to the date format allowed in data store.

That check needs to accommodate the date value: `2019-07-16T11:03:09Z` which is the `updateDate` of this metadata: https://api.ingest.staging.data.humancellatlas.org/files/5d2dae915f9ee9000809b682

This is not consistent with other updateDate values of other documents which we currently check `"%Y-%m-%dT%H:%M:%S.%fZ"`: https://api.ingest.staging.data.humancellatlas.org/processes/5d2dae915f9ee9000809b695/derivedFiles

Code to modify: https://github.com/HumanCellAtlas/ingest-client/blob/master/ingest/api/utils.py#L3

**Comment by aaclan-ebi** [comment]
Looks like this format is expected based on the documentation of how Instant objects are being converted to string: 

"The nano-of-second outputs zero, three, six or nine digits as necessary. "

http://cr.openjdk.java.net/~iris/se/11/latestSpec/api/java.base/java/time/Instant.html#toString()
http://cr.openjdk.java.net/~iris/se/11/latestSpec/api/java.base/java/time/format/DateTimeFormatter.html#ISO_INSTANT

**Comment by aaclan-ebi** [comment]
Fix was released to staging today.
