### ISSUE TITLE
Store metadata UUID as part of staging details used for exporting

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#535]
Metadata update operation in the exporter relies on the mapping between the files staged through the Upload Service and the UUIDs of the metadata they are meant to contain update data for. The exporter uses this mapping to determine which files in the bundle to update with which files in the staging area. 

For relatively small updates that will likely never share files across multiple bundles, the current operation will still work. This will be an issue for when there are multiple (not necessarily concurrent) attempts to stage the same file to the same staging area because subsequent attempts to stage the file will return successfully without the necessary mapping to the metadata UUID.

**Comment by aaclan-ebi** [comment]
This happened for this project `47382634-bd80-4472-b6ae-928351bb3fe5` in production.

The project was updated and is shared across 5 bundles for this `WongAdultRetina` dataset. Only the first bundle succeeded.

Since there are only 4 bundles that need to be exported, we did the workaround to delete the staging lock before every retry.

 2019-09-09 12:47:02,506  - receiver.UpdateBundleReceiver - ERROR in receiver.py:119 on_message(): Failed to process the exporter message: {"bundleUuid":"afb5241b-8989-4a84-ada5-5c3d503a1048","versionTimestamp":"2019-09-09T12:46:53.581961Z","documentId":"5d76472aaa252400084a0a69","documentUuid":"afb5241b-8989-4a84-ada5-5c3d503a1048","documentType":"BundleManifest","callbackLinks":["/projects/5d76496caa252400084a0a6e"],"envelopeId":"5d76496aaa252400084a0a6c","envelopeUuid":"4ff39c0e-8996-4486-8f6d-e70684dbbfce","index":2,"total":5,"messageProtocol":null} due to error: 'NoneType' object has no attribute 'get'
 2019-09-09 12:47:05,272  - receiver.UpdateBundleReceiver - ERROR in receiver.py:119 on_message(): Failed to process the exporter message: {"bundleUuid":"1925d682-3054-41a3-89a1-0ea15e139fdd","versionTimestamp":"2019-09-09T12:46:53.582837Z","documentId":"5d764723aa252400084a0a67","documentUuid":"1925d682-3054-41a3-89a1-0ea15e139fdd","documentType":"BundleManifest","callbackLinks":["/projects/5d76496caa252400084a0a6e"],"envelopeId":"5d76496aaa252400084a0a6c","envelopeUuid":"4ff39c0e-8996-4486-8f6d-e70684dbbfce","index":3,"total":5,"messageProtocol":null} due to error: 'NoneType' object has no attribute 'get'
 2019-09-09 12:47:02,734  - receiver.UpdateBundleReceiver - ERROR in receiver.py:119 on_message(): Failed to process the exporter message: {"bundleUuid":"bc47a2cb-274f-42b6-b900-27d4e6c63030","versionTimestamp":"2019-09-09T12:46:53.583673Z","documentId":"5d764739aa252400084a0a6b","documentUuid":"bc47a2cb-274f-42b6-b900-27d4e6c63030","documentType":"BundleManifest","callbackLinks":["/projects/5d76496caa252400084a0a6e"],"envelopeId":"5d76496aaa252400084a0a6c","envelopeUuid":"4ff39c0e-8996-4486-8f6d-e70684dbbfce","index":4,"total":5,"messageProtocol":null} due to error: 'NoneType' object has no attribute 'get'
 2019-09-09 12:47:02,668  - receiver.UpdateBundleReceiver - ERROR in receiver.py:119 on_message(): Failed to process the exporter message: {"bundleUuid":"fd3ff860-ee55-4998-b90e-8cd2ae7d06c0","versionTimestamp":"2019-09-09T12:46:53.581010Z","documentId":"5d76472aaa252400084a0a6a","documentUuid":"fd3ff860-ee55-4998-b90e-8cd2ae7d06c0","documentType":"BundleManifest","callbackLinks":["/projects/5d76496caa252400084a0a6e"],"envelopeId":"5d76496aaa252400084a0a6c","envelopeUuid":"4ff39c0e-8996-4486-8f6d-e70684dbbfce","index":1,"total":5,"messageProtocol":null} due to error: 'NoneType' object has no attribute 'get'

**Comment by aaclan-ebi** [comment]
error stacktrace:
```
2019-09-09 12:47:01,725  - ingest.exporter.staging - WARNING in staging.py:113 stage_metadata(): A file with name "project_47382634-bd80-4472-b6ae-928351bb3fe5.json" already exists in staging area 4ff39c0e-8996-4486-8f6d-e70684dbbfce.
 2019-09-09 12:47:02,505  - receiver.UpdateBundleReceiver - ERROR in receiver.py:118 on_message(): 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/receiver.py", line 115, in on_message
    body_dict.get('callbackLinks'), bundle_version)
  File "/app/src/hca-ingest/ingest/exporter/exporter.py", line 43, in export_update
    self.bundle_service.update(bundle, staging_details)
  File "/app/src/hca-ingest/ingest/exporter/bundle.py", line 128, in update
    'update_date': file.get('version')})
AttributeError: 'NoneType' object has no attribute 'get'
 2019-09-09 12:47:02,506  - receiver.UpdateBundleReceiver - ERROR in receiver.py:119 on_message(): Failed to process the exporter message: {"bundleUuid":"afb5241b-8989-4a84-ada5-5c3d503a1048","versionTimestamp":"2019-09-09T12:46:53.581961Z","documentId":"5d76472aaa252400084a0a69","documentUuid":"afb5241b-8989-4a84-ada5-5c3d503a1048","documentType":"BundleManifest","callbackLinks":["/projects/5d76496caa252400084a0a6e"],"envelopeId":"5d76496aaa252400084a0a6c","envelopeUuid":"4ff39c0e-8996-4486-8f6d-e70684dbbfce","index":2,"total":5,"messageProtocol":null} due to error: 'NoneType' object has no attribute 'get'
 2019-09-09 03:30:26,149  - ingest.api.stagingapi - INFO in stagingapi.py:97 __init__(): 
```

**Comment by rdgoite** [comment]
Based on the current ongoing work on the Barcelona datasets, and the issue that the wranglers encountered yesterday, I decided to bump up the priority of this issue and put it in the current sprint. Also, working on this now will allow us to release the fix to production early next week going through the usual release schedule, just in time for the Barcelona datasets to finish ingestion.
