### ISSUE TITLE
[Login] Can't login to staging ui

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ingest-central#586]
**[Login]Can't login to staging ui**

**To Reproduce**

Please explain as much as you can about what you were doing when the bug was observed (to help us reproduce the error for testing).

Steps to reproduce the behaviour:
1. Go to https://ui.ingest.staging.data.humancellatlas.org/login
2. Click on login, then use my mshadbolt@ebi.ac.uk google account
3. I get sent to this page: https://auth.integration.data.humancellatlas.org/internal/cb?code=fOqGFK82GGP_TEoT&state=eyJvcGVuaWRfcHJvdmlkZXIiOiAiaHVtYW5jZWxsYXRsYXMuYXV0aDAuY29tIiwgInJlZGlyZWN0X3VyaSI6ICJodHRwczovL3VpLmluZ2VzdC5zdGFnaW5nLmRhdGEuaHVtYW5jZWxsYXRsYXMub3JnL2NhbGxiYWNrIiwgInJlc3BvbnNlX3R5cGUiOiAiY29kZSJ9
and see this error:
```
Traceback (most recent call last):
  File "/var/task/chalicelib/fusillade/api/__init__.py", line 126, in dispatch
    flask_res = self.connexion_full_dispatch_request()
  File "/var/task/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/task/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/task/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/task/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/var/task/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/var/task/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/var/task/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/var/task/chalicelib/fusillade/api/oauth.py", line 164, in cb
    key=public_keys[token_header["kid"]],
KeyError: 'MDc2OTM3ODI4ODY2NUU5REVGRDVEM0MyOEYwQTkzNDZDRDlEQzNBRQ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/chalicelib/fusillade/api/__init__.py", line 131, in dispatch
    exception=ex
  File "/var/lang/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/var/lang/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/lang/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/var/lang/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'KeyError' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1070, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/chalicelib/fusillade/api/__init__.py", line 139, in dispatch
    status_code=status_code,
UnboundLocalError: local variable 'status_code' referenced before assignment
```

**Expected behaviour**

Be able to login to the staging UI

**Actual behaviour**

Please explain what actually happened.

I can't login to the staging ui

**Impact**

It is blocking anyone who wants to upload using the ui in staging

**Screenshots or Messages**

see above

**Comment by mshadbolt** [comment]
This seems to be an intermittent issue because now I can login.

**Comment by aaclan-ebi** [comment]
This is related to an issue in Fusillade. https://github.com/HumanCellAtlas/fusillade/issues/283

**Comment by justincc** [comment]
I'm presuming this was handled some time ago.
