### ISSUE TITLE
API Key setup on metadata-schema-publisher repo

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#611]
Steps to Repro:
1. Trigger a push event from Github (Mock event , see metadata-schema-publisher repo how)
2. Schema publisher runs and publish schema to s3 buckets

Actual Behavior:
Error: 
```
403 {"message": "API rate limit exceeded for 54.162.180.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://developer.github.com/v3/#rate-limiting"}: RateLimitExceededException Traceback (most recent call last): File "/var/task/handler.py", line 65, in on_github_push result = _process_d
403
{
    "message": "API rate limit exceeded for 54.162.180.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
: RateLimitExceededException
Traceback (most recent call last):
File "/var/task/handler.py", line 65, in on_github_push
result = _process_directory(repo, branch.name, server_path, server_path, version_numbers, context, dryrun)
File "/var/task/handler.py", line 101, in _process_directory
_process_directory(repo, branch_name, base_server_path, content.path, version_numbers, context, dryrun))
File "/var/task/handler.py", line 101, in _process_directory
_process_directory(repo, branch_name, base_server_path, content.path, version_numbers, context, dryrun))
File "/var/task/handler.py", line 97, in _process_directory
contents = repo.get_dir_contents(server_path, branch_name)
File "/var/task/github/Repository.py", line 1793, in get_dir_contents
parameters=url_parameters
File "/var/task/github/Requester.py", line 268, in requestJsonAndCheck
return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
File "/var/task/github/Requester.py", line 279, in __check
raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403
{
    "message": "API rate limit exceeded for 54.162.180.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

Expected Behavior:
Schema changes should be published.

Notes:
Looks like the fix for the ticket #455 to remove the API KEY for using Github API was deployed in a different env and the issue isn't caught before.

While trying to test the issue #610 that API KEY removal fix was deployed to the correct env and now the publisher is experiencing the rate limit for unauthenticated Github API requests. Need to fix the issue to not block any metadata schema release.

**Comment by aaclan-ebi** [comment]
Merged and deployed https://github.com/HumanCellAtlas/metadata-schema-publisher

Setup access token:
https://github.com/HumanCellAtlas/metadata-schema-publisher/pull/5

Fix slack notification as well:
https://github.com/HumanCellAtlas/metadata-schema-publisher/pull/7

**Comment by aaclan-ebi** [comment]
Removed the sensitive info in the repo history by following this guide. 
https://github.com/IBM/BluePic/wiki/Using-BFG-Repo-Cleaner-tool-to-remove-sensitive-files-from-your-git-repo
