### ISSUE TITLE
Fix exporter to use the dcpVersion and not the updateDate when uploading bundle files

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#647]
When exporting new bundles which refer to existing entities in Ingest. The existing entities shouldn't be uploaded with a newer version. New bundles should refer to the same uuid + version of the bundle file.

**Comment by aaclan-ebi** [comment]
Looks like the exporter code is broken , fixing this.

```
 2019-12-02 15:47:05,674  - receiver.CreateBundleReceiver - ERROR in receiver.py:75 on_message(): Failed to process the exporter message: {"bundleUuid":"985a81de-3008-489e-8be0-a629553b6605","versionTimestamp":"2019-12-02T15:46:45.536836Z","messageProtocol":null,"documentId":"5de5312612198e6c187c857e","documentUuid":"96dc4c43-02df-427e-92ac-79e7c335e5f0","callbackLink":"/processes/5de5312612198e6c187c857e","documentType":"Process","envelopeId":"5de5312412198e6c187c856f","envelopeUuid":"1d6536a3-bcf7-4fc9-bb30-9833f99ffb63","index":0,"total":1} due to error: An error occurred while putting file in DSSnot_found: Cannot find file! (HTTP 404). Details:
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/cloud_blobstore/s3.py", line 223, in get
    Key=key
  File "/opt/python/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/task/chalicelib/dss/api/files.py", line 76, in get_helper
    f"files/{uuid}.{version}"
  File "/opt/python/lib/python3.6/site-packages/cloud_blobstore/s3.py", line 26, in wrapped
    return meth(*args, **kwargs)
  File "/opt/python/lib/python3.6/site-packages/cloud_blobstore/s3.py", line 228, in get
    raise BlobNotFoundError(f"Could not find s3://{bucket}/{key}") from ex
cloud_blobstore.BlobNotFoundError: Could not find s3://org-humancellatlas-dss-dev/files/35556d9c-a182-45ef-8f7a-c1468299da14.2019-12-02T154334.837000Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/files.py", line 48, in get
    return get_helper(uuid, Replica[replica], version, token, directurl, content_disposition)
  File "/var/task/chalicelib/dss/api/files.py", line 90, in get_helper
    raise DSSException(404, "not_found", "Cannot find file!")
dss.error.DSSException
```

**Comment by aaclan-ebi** [comment]
https://github.com/HumanCellAtlas/ingest-client/pull/68/files

**Comment by aaclan-ebi** [comment]
Merged and now deployed to dev.
