### ISSUE TITLE
Local host required to run summary stats script

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/ingest-central#69]
After a git clone of ingest-broker, when trying to run `ingest-broker/generate_summary.py` using

`python3 generate_summary.py http://api.ingest.dev.data.humancellatlas.org submission d518fbdf-b716-4e15-a025-0d5b49bf9f8d tsv`,

I get the error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10518cbe0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10518cbe0>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_summary.py", line 49, in <module>
    summary = generate_project_summary(uuid_str, ingest_url) if summary_type == 'project' else generate_submission_summary(uuid_str, ingest_url)
  File "generate_summary.py", line 13, in generate_submission_summary
    summary = SummaryService().summary_for_submission(submission)
  File "/Users/hewgreen/google_drive/ingest-broker/broker/service/summary_service.py", line 15, in __init__
    self.ingestapi = IngestApi() if not ingest_api else ingest_api
  File "/Users/hewgreen/google_drive/ingest-broker/src/hca-ingest/ingest/api/ingestapi.py", line 31, in __init__
    self.ingest_api_root = ingest_api_root if ingest_api_root is not None else self.get_root_url()
  File "/Users/hewgreen/google_drive/ingest-broker/src/hca-ingest/ingest/api/ingestapi.py", line 38, in get_root_url
    reply = requests.get(self.url, headers=self.headers)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10518cbe0>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

Alegria suggested that this was because I need a local host running to get the script working. Please provide a fix or workaround to get the script running.

Thanks,

Matt

**Comment by hewgreen** [comment]
Work around is really nice (but it doesn't work for Mallory):

`http://ingest.dev.data.humancellatlas.org/projects/<project_uuid>/summary`
or
`http://ingest.dev.data.humancellatlas.org/submissions/<submission_uuid>/summary`

**Comment by rolando-ebi** [comment]
@hewgreen @malloryfreeberg This is now fixed.
